# name: 'add issue to kanban'

# on:
#   issues:
#     types: [opened]

# jobs:
#   add-to-project:
#     name: Add issue to project
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/add-to-project@v0.3.0
#         with:
#           # https://github.com/orgs|users/<ownerName>/projects/<projectNumber>
#           project-url: https://github.com/users/masaki12-s/projects/3
#           status_field: Todo
#           # repo and projectのtokenが必要
#           github-token: ${{ secrets.AUTOMATION_TOKEN }}

name: 'Automatically add issue to basebankdev project'

on:
  issues:
    types: [opened, assigned]

env:
  PROJECT_NAME: local_project
jobs:
  # automate-project-columns:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Move issues into pj column
  #       uses: alex-page/github-project-automation-plus@v0.8.1
  #       with:
  #         project: local_project
  #         column: Todo
  #         repo-token: ${{ secrets.AUTOMATION_TOKEN }}
  assign_issue_to_project:
    name: Assign issues to projcet
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to project
        uses: technote-space/create-project-card-action@v1
        if: "github.event.action == 'opened'"
        with:
          PROJECT: ${{env.PROJECT_NAME}}
          COLUMN: Todo
          repo-token: ${{ secrets.AUTOMATION_TOKEN }}