name: 'add issue to kanban'
on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          # https://github.com/orgs|users/<ownerName>/projects/<projectNumber>
          project-url: https://github.com/users/masaki12-s/projects/3
          # repo and projectのtokenが必要
          github-token: ${{ secrets.AUTOMATION_TOKEN }}
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: local_project
          column: Todo
          repo-token: ${{ secrets.AUTOMATION_TOKEN }}
# name: Move new issues into Triage
# on:
#   issues:
#     types: [opened]
# jobs:
#   automate-project-columns:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: alex-page/github-project-automation-plus@v0.8.1
#         with:
#           project: local_project
#           column: Todo
#           repo-token: ${{ secrets.AUTOMATION_TOKEN }}
# on:
#   issues:
#     types: [opened]
# jobs:
#   Add_New_Issue_To_Project:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: konradpabjan/actions-add-new-issue-to-column@v1.1
#       with:
#         action-token: "${{ secrets.AUTOMATION_TOKEN }}"
#         project-url: "https://github.com/users/masaki12-s/projects/3"
#         column-name: "Todo"