name: Move Assigned Issues to Column
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to "Assigned" column
        uses: alex-page/github-project-automation-plus@v0.6.0
        with:
          project: https://github.com/users/masaki12-s/projects/3/views/1
          column: 'In Progress'
          repo-token: ${{ secrets.AUTOMATION_TOKEN }}