name: Move assigned card
on:
  issues:
    types:
      - assigned
move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Docs Work
          column: In Progress
          repo-token: ${{ secrets.AUTOMATION_TOKEN }}